### ISSUE TITLE
Add a license file

### ISSUE THREAD

**Issue by cecilia-donnelly** [hassansin/parse-address#1]
Hi!  [Here](https://www.npmjs.com/package/parse-address) it says that this package is being distributed under the ISC license -- is that true?  If so, would you accept a pull request to add a file with the text of the license and some license headers?

Thanks!

P.S. -- excited to use the library, thanks for porting it to node js!

**Comment by hassansin** [comment]
Yes, please send a pull request. 

Thanks.

**Comment by cecilia-donnelly** [comment]
Submitted: https://github.com/hassansin/parse-address/pull/2

Let me know if you need any changes.
