### ISSUE TITLE
Parse-address is too awesome. Please reduce it's awesomeness so other options don't suck so much.

### ISSUE THREAD

**Issue by cube-dan** [hassansin/parse-address#26]
Hassansin,

I spent a whole afternoon wrestling with multiple geocoding services to try and get a reasonable parse of address strings — your lib (hassansin/parse-address) did the job in 20min!

I can't thank you enough for your hard work on parse-address. You've done a wonderful job and you have my heartfelt thanks.

-Dan

**Comment by hassansin** [comment]
Hi Dan, 
Thanks a lot for such nice and inspiring words! It really makes me happy to see this little library is helping out the javascript community. Being frustrated myself I ported the awesome Perl package to javascript. So really all credit goes to the original author who wrote the Perl package.
